project_urls:
  Bug Tracker: https://github.com/AllenCell/organelle-segmenter-plugin/issues
  Documentation: https://github.com/AllenCell/organelle-segmenter-plugin#README.md
  Source Code: https://github.com/AllenCell/organelle-segmenter-plugin
  User Support: https://github.com/AllenCell/organelle-segmenter-plugin/issues

# Add labels from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - 3D image
  - Cell segmentation
  - Model-based segmentation
  - Fluorescence microscopy
  - Image visualisation
